### ISSUE TITLE
https://hdtoday.tv/

### ISSUE THREAD

**Issue by LowFake** [streambase-project/streambase#107]

**Comment by streambase-project** [comment]
@LowFake Wielokrotnie strona była proponowana, niestety nie wyróżnia się niczym na tle podobnych, obecnie dodajemy do spisu angielskiego już jedynie strony wyjątkowe. Odrzucamy.

**Comment by gzenio22** [comment]
ta strona dziala na konsolach nie ma reklam w odtwarzaczu z tego co wiem to ją wyróżnia

**Comment by gzenio22** [comment]
nie mam konsoli nie sprawdze

**Comment by streambase-project** [comment]
@streambase-project to ja powiem od siebie, że inne też raczej działają w niemal identycznie.
