### ISSUE TITLE
kilka stron do dodania bo brakuje

### ISSUE THREAD

**Issue by Quassar89** [streambase-project/streambase#109]
Oto kilka stron chyba najbardziej popularnych w dziejach warez 
bo to zwykle od tych crackerów rozchodzi sie spora część wstawek na cały Internet

ELCHUPACABRA przesiaduje na 
https://lrepacks.net
Jest to blog z  oprogramowaniem

Ratiborus
http://forum.ru-board.com
Rosyjski warez najdziecie tutaj przede wszystkim aktywator do windowsa i nie tylko od głównego crackera.

Daz - jego też raczej nie trzeba przedstawiać :D
https://forums.mydigitallife.net
Kolejne forum tutaj znajdziecie m.in aktywatory do windowsa i offica  i innego typu softu do debloat windowsa.

Kolejne zacne forum z programami pełnymi - tutaj akurat wymaga zwykłe konto, aby dostać sie do treści ukrytej.
Też posiada własnych crackerów, repackerów są też reuploady z powyższych for i innych,
[nsaneforums.com](https://nsaneforums.com)

Nie wiem czy XXX wstawiacie...

Ale tutaj macie jedne z for warezowych gdzie macie rehosting do największych baz premium porno za free m.in MetArt, Femjoy itd
https://kitty-kats.net
https://vipergirls.to/forum.php
http://www.planetsuzy.org/
oraz 
http://www.fritchy.com
https://forum.phun.org
http://www.nudecelebforum.com

Blogi:
http://idol98.com/ - rehost http://258336.xyz
https://top-modelz.org/
http://13dl.net/category/adult/adult-photo/kaigaip
https://eroticashare.com/
https://www.erofullsets.com/
https://eropics.to
https://softmodels.net

Fajna strona gdzie można obejrzeć bez pobierania pełne albumy premium NSFW i pobrać pojedynczo fotki 
https://nsfwalbum.com/

https://www.thenude.com/ - Biografia-encyklopedia dziwek, jak chcesz znaleźć info o danej kurwie i zobaczyć katalog jej wszystkich zdjęć i filmów gdzie wystąpiła 
https://www.babepedia.com - jak wyżej

**Comment by streambase-project** [comment]
@Quassar89 do końca tygodnia zostanie przejrzane zgłoszenie, na ten moment mogę powiedzieć, że strony rosyjskie muszę odrzucić, akceptujemy tylko strony z możliwym do wyboru językiem co najwyżej angielskim.

**Comment by streambase-project** [comment]
@Quassar89 stron typowo z językiem rosyjskim nie umieszczamy, głównie tylko te, które są angielskie, te nie są raczej czymś odkrywczym, mimo że są może „dobrze znane”, erotyka też nie u nas, także odrzucam, dodamy tylko dwa pozostałe fora techiczne, nadają się.

**Comment by Quassar89** [comment]
Oczywiście że te fora nie są odkrywcze ale wiadomo że lepiej pobierać bezpośrednio od osoby co pisze patche niż pobierać z lewych blogów a ruskiego nie trzeba znać wpisujesz w pasku nazwę programu i pobierasz jak jest i tyle...

A co do tłumaczenia to przeglądarki już mają wbudowane auto translatory jak ktoś sie uprze.

**Comment by streambase-project** [comment]
@streambase-project dodane, na przyszłość twórz osobne zgłoszenie do pojedynczych stron.
