### ISSUE TITLE
Strona z repackami

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#110]
https://socigames.com/

**Comment by streambase-project** [comment]
@Wardzislaw słaba aktywność w porównaniu do innych z tej kategorii, coś wyróżnią tę stronę?

**Comment by Wardzislaw** [comment]
> @Wardzislaw słaba aktywność w porównaniu do innych z tej kategorii, coś wyróżnią tę stronę?

Nie wiem, ja tylko znalazłem i tu wysłałem

**Comment by streambase-project** [comment]
@Wardzislaw to na przyszłość jeżeli już chcesz, to podsyłaj ciekawe/wartościowe strony, bo takich byle jakich to jest mnóstwo, spisy liczyłyby po 50 pozycji gdybym dodawał wszystkie strony, które jako tako działają.
