### ISSUE TITLE
http://matlo44funkytown.eklablog.com/

### ISSUE THREAD

**Issue by Quassar89** [streambase-project/streambase#115]
Blog z muzyką bardziej w kierunku funky / bluez
Mniej znany z racji gatunku co nie zmienia faktu że blog ma ponad 10 lat i można na nim znaleźć sporo albumów które cięzko znaleźć na innych blogach jeśli ofc ktoś lubi funky.

Minus taki że ma auto play muzykę w tyle przy wejściu, ale można zatrzymać na tej żółtej kasecie po prawej stronie.

**Comment by streambase-project** [comment]
@Quassar89 odrzucam, raczej nic ciekawego.
