### ISSUE TITLE
Radiostacja https://www.di.fm + Skrypt do odblokowania funkcji premium

### ISSUE THREAD

**Issue by Quassar89** [streambase-project/streambase#116]
Chyba najstarsze radio internetowe poświęcone muzyce elektronicznej.. 
DI.FM pełna nazwa to Digitally Imported
Radio założone pod koniec 1999 roku! Czyli pewnie starsza niż połowa użytkowników streambase :D
Bardzo duża lista podstacji pod poszczególne podgatunki.
To właśnie na niej Disc Jokey`e [DJe] Grają na żywo swoje utwory zanim wyjdą na świat.
Radiostacja też inne domeny pod inne gatunku muzyczne.

!! WARTE UWAGI !!
Skrypt Do powyższej strony DI.FM
https://github.com/lethak/LTKDIFMU-userscript
Odblokowywane cześć funkcji premium oraz dodaje parę swoich:
-Wyłącza reklamy.
-Daje możliwość cofania lub słuchania dowolnej muzyki, a nie tylko obecnej.
-Dodaje możliwość pobrania danego utworu
-Możliwość pomijania więcej niż jednego utworu.
i pare innych.

**Comment by streambase-project** [comment]
@Quassar89 odrzucam, skrypt jest łatwy do znalezienia szukając samemu + samo radio raczej mało popularne u nas.
