### ISSUE TITLE
http://music.ishkur.com

### ISSUE THREAD

**Issue by Quassar89** [streambase-project/streambase#117]
Encyklopedia / Przewodnik po muzyce elektronicznej. 
Strona poświęcona muzyce która ma chyba z 30 lat
jakieś 5 lat temu zmienili szate.

Jak korzystać:
Na kółku od myszki przybliżać Poruszać się przeciągając przyciskiem lewym.
i masz datę i powstanie danych gatunków i podgatunków muzyki
Po naciśnięciu na pasek masz info o powstaniu oraz kilka przykładowych utworów.

Strona opisuje powstanie oraz chyba niemalże całą ewolucje muzyki elektronicznej z przykładami muzyki.
Dobre dla ludzi co chcą poznać muzykę elektroniczną oraz nauczyć się rozpoznawać, predefiniować ją na poszczególne podgatunki.

**Comment by streambase-project** [comment]
@Quassar89 dodane.
