### ISSUE TITLE
TV online

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#140]
https://leaks.ma7.eu/lista.php

**Comment by streambase-project** [comment]
@Wardzislaw dodane.

**Comment by mailliks55** [comment]
Strona dnia 30.06 do 1.07.2023 przechodzi remont i będzie wyłączona przepraszamy za usterki i zapraszamy niebawem z nowymi możliwościami i nową domeną pozdrawiamy Administracja.

**Comment by mailliks55** [comment]
adres tymczasowy https://leks7.c1.is/lista.php 
ponieważ prace jednak potrwają dłużej za co przepraszamy.

**Comment by mailliks55** [comment]
proszę o poprawę linku na https://leks7.c1.is/lista.php

**Comment by Kolo3000** [comment]
Nie działa

**Comment by mailliks55** [comment]
Ponieważ strona znajduje się pod nowym adresem. https://leks7.eu/list.php tak że do zmiany
