### ISSUE TITLE
tmj

### ISSUE THREAD

**Issue by KonoromiHimaries** [streambase-project/streambase#143]
```
https://wbijam.pl/#wbijam-tmj-rip
```

**Comment by gzenio22** [comment]
projekt zamknięty do wywalenia z propozycji

**Comment by streambase-project** [comment]
@KonoromiHimaries @gzenio22 w chwili obecnej mimo tego komunikatu nadal można oglądać treści, które są dostępne, pozostawiam, póki jest taka możliwość.
