### ISSUE TITLE
https://you.com | NOWA WYSZUKIWARKA 

### ISSUE THREAD

**Issue by PLoliwi** [streambase-project/streambase#15]

**Comment by streambase-project** [comment]
@PLoliwi nie jest to na tyle interesujące odkrycie, by dodać do bazy, na razie odrzucam.

**Comment by PLoliwi** [comment]
> @PLoliwi nie jest to na tyle interesujące odkrycie, by dodać do bazy, na razie odrzucam.

Jest tu CHATPT inny od https://chat.openai.com/chat

to jest od you.com | https://you.com/search?q=who+are+you&tbm=youchat&cfr=chat

**Comment by PLoliwi** [comment]
@streambase-project

**Comment by PLoliwi** [comment]
Jest też 
![image](https://user-images.githubusercontent.com/95148122/221715379-7c75e15b-6d6d-4ae3-8c6c-e16dbd1c3b98.png)

**Comment by PLoliwi** [comment]
I po polsku 
![image](https://user-images.githubusercontent.com/95148122/221715435-63575aa2-13fc-444c-b3e8-3248f5cf2a57.png)

**Comment by streambase-project** [comment]
@PLoliwi dodane.
