### ISSUE TITLE
Strona do pobierania repacków - w jednym miejscu

### ISSUE THREAD

**Issue by robak29** [streambase-project/streambase#150]
https://gamesdrive.net/Forum-Repacks

**Comment by Wardzislaw** [comment]
@robak29 To już jest.

**Comment by streambase-project** [comment]
@Wardzislaw gdzie?

**Comment by Wardzislaw** [comment]
@streambase-project 
![image](https://github.com/streambase-project/index/assets/128229756/e18aca72-9e36-479e-8715-a07f67989438)

**Comment by streambase-project** [comment]
@Wardzislaw faktycznie przeoczenie nasze.
@robak29 wyjaśnione.
