### ISSUE TITLE
https://darkwarez.net/

### ISSUE THREAD

**Issue by robak29** [streambase-project/streambase#162]
Nowy warez

**Comment by Wardzislaw** [comment]
Eeeee... Darkwarez wróciło?

**Comment by streambase-project** [comment]
@robak29 brak możliwości rejestracji, tymczasowo odrzucamy.

**Comment by Wardzislaw** [comment]
@streambase-project Rejestracja została włączona.

**Comment by prezes92k** [comment]
Dziś (07.08.23) zarejestrowałem się

**Comment by streambase-project** [comment]
@Wardzislaw @prezes92k adres darkbox został zmieniony na darkwarez.

**Comment by Zawada890** [comment]
Darkbox a darkwarez to dwie inne strony
