### ISSUE TITLE
Kolejny warez Existe

### ISSUE THREAD

**Issue by prezes92k** [streambase-project/streambase#163]
https://exsite.su/

**Comment by robak29** [comment]
I po co to komu ?

**Comment by streambase-project** [comment]
@prezes92k mamy to w bazie pod adresem .vip, zaktualizowałem domene.

**Comment by cielon80** [comment]
przeciez to klon  exsite.pl z ta roznica ze su prowadza ludzie z darkboxa

**Comment by streambase-project** [comment]
@cielon80 klon, ale z innym szablonem i z innymi wrzutami, to wystarczy by widniał w bazie.
