### ISSUE TITLE
https://european-alternatives.eu/alternatives-to

### ISSUE THREAD

**Issue by corteum** [streambase-project/streambase#17]
https://european-alternatives.eu/alternatives-to do #awesomelinks Zestaw europejskich alternatyw dla popularnych usług IM, VPN, VPS, DNS, PassManager, Object Storage, nawigacja itp.

**Comment by streambase-project** [comment]
@corteum w kwestii VPN-ów, jest już dobre źródło w awesome-links, natomiast w kwestii alternatyw do różnych rzeczy to mało wartościowa rzecz.
