### ISSUE TITLE
Zagraniczne strony do oglądania filmów 

### ISSUE THREAD

**Issue by robak29** [streambase-project/streambase#174]
https://flixhq.to/

https://flixhq.ru/

https://flixhq.pro/

https://flixhq.ws/

**Comment by TestNintendo** [comment]
to jest ta sama strona pod różnymi domenami
myślę, że przyjmą tylko jedną z domen

**Comment by streambase-project** [comment]
@robak29 pomijając to, co napisał @TestNintendo, nie dodajemy już takich stron do bazy, mam na myśli takich, które są identyczne do tych, które już są, obecnie baza materiałów jest niemal wszędzie identyczna, jeżeli strona czymś by się wyróżniała, to wtedy możemy rozważyć dodanie. Odrzucamy.
