### ISSUE TITLE
wyszukiwarka filmów i seriali online

### ISSUE THREAD

**Issue by 89891383** [streambase-project/streambase#183]
https://strimki.top/wyszukiwarka/

**Comment by streambase-project** [comment]
@89891383 nic nie ma na tej stronie.

**Comment by 89891383** [comment]
> @89891383 nic nie ma na tej stronie.
sprawdź co dodali tam

**Comment by streambase-project** [comment]
@89891383, póki co odrzucamy, nie działa to jakoś dobrze.
