### ISSUE TITLE
Niezaufane/podszywające się strony z grami do usunięcia

### ISSUE THREAD

**Issue by zaye93** [streambase-project/streambase#185]
Źródła (r/Piracy i r/PiratedGames)
https://www.reddit.com/r/Piracy/wiki/megathread/games/#wiki_.2623.FE0F_.279C_untrustworthy_websites
https://rentry.org/pgames/#untrusted-sites

Niezaufane strony:
https://repack-mechanics.com/
https://repack-games.com/
https://elamigosedition.com/
https://www.skidrowreloaded.com/
https://www.skidrowcodex.net/
https://www.aimhaven.com/
https://steamunlocked.net/
https://igg-games.com/
https://pcgamestorrents.com/
https://game3rb.com/
http://oceanofgames.com/

**Comment by streambase-project** [comment]
@zaye93 ogólnie mówiąc, w świecie piractwa trzeba zawsze brać poprawkę, że pobierany plik jest zainfekowany, obecnie bezpieczne strony można zliczyć na palcach obu rąk i nie wszystkie są publiczne. Niektóre strony w bazie owszem mają to ryzyko większe lub mniejsze, natomiast pliki same w sobie są bardzo często wiarygodne i jakościowe, na tej podstawie te strony zostały dodane, dopóki każda z tych stron dodaje opisane pliki i są to rzeczywiście one, mimo wszelkich załączników typu wirusy, te strony nie zostaną usunięte, po prostu to jest pewnego rodzaju nieuniknione zło, które musimy zaakceptować. W przyszłości możliwe, że dodamy oznaczenia, które strony są w 100% bezpieczne, by mieć spokój, natomiast na ten moment sam nie wierzę, że takie istnieją mimo tego, jak dobra jest o nich opinia. Mimo wszystko dziękujemy za to zgłoszenie.

**Comment by Wardzislaw** [comment]
> Tak, tylko uważam, że te strony są po prostu niepotrzebne, skoro nie zawierają żadnego unikalnego kontentu. Wszystko można znaleźć na reszcie bardziej zaufanych stronach z listy. W sumie żadna strona nie jest 100% bezpieczna, ale możemy odrzucić te, które mają potwierdzone wciskanie jakiegoś syfu. Nie wspomniałem o torrentach jak 1337x (ostatnia drama z VitaminX), bo tam bezpieczeństwo zależy głównie od uploadera, więc nie ma co usuwać takiej strony.

Pierdolisz, te strony powinny zostać.

**Comment by streambase-project** [comment]
> Tak, tylko uważam, że te strony są po prostu niepotrzebne, skoro nie zawierają żadnego unikalnego kontentu. Wszystko można znaleźć na reszcie bardziej zaufanych stronach z listy. 

Te strony, o których ty mówisz, że są niepotrzebne to takie multi-strony, na nich znajdziesz nie tylko to, co wypuszcza scena, ale również inne rzeczy, chodzi o to, że posiadają więcej treści, a na zaufanych stronach zwykle nie wychodzi się poza zaufane/scenowe pliki. Dlatego trzymamy te strony, jeden wybierze stronę typowo zaufaną i będzie ją przeglądał ograniczając się tylko do konkretnych wstawek, a drugi wejdzie na taką co ma większy wybór i więcej treści.

> W sumie żadna strona nie jest 100% bezpieczna, ale możemy odrzucić te, które mają potwierdzone wciskanie jakiegoś syfu.

Możemy, ale te strony mają więcej treści, równie dobrych mimo "wirusów", dlatego tak jak mówię, są one w bazie. Najlepszym rozwiązaniem byłoby po prostu oznaczenie tych bezpiecznych w 100% jeżeli to ułatwi komuś życie, chociaż i tak trzeba uważać więc z drugiej strony mija się to z celem.

**Comment by streambase-project** [comment]
@zaye93 

> Tak, tylko uważam, że te strony są po prostu niepotrzebne, skoro nie zawierają żadnego unikalnego kontentu. Wszystko można znaleźć na reszcie bardziej zaufanych stronach z listy. 

Te strony, o których ty mówisz, że są niepotrzebne to takie multi-strony, na nich znajdziesz nie tylko to, co wypuszcza scena, ale również inne rzeczy, chodzi o to, że posiadają więcej treści, a na zaufanych stronach zwykle nie wychodzi się poza zaufane/scenowe pliki. Dlatego trzymamy te strony, jeden wybierze stronę typowo zaufaną i będzie ją przeglądał ograniczając się tylko do konkretnych wstawek, a drugi wejdzie na taką co ma większy wybór i więcej treści.

> W sumie żadna strona nie jest 100% bezpieczna, ale możemy odrzucić te, które mają potwierdzone wciskanie jakiegoś syfu.

Możemy, ale te strony mają więcej treści, równie dobrych mimo "wirusów", dlatego tak jak mówię, są one w bazie. Najlepszym rozwiązaniem byłoby po prostu oznaczenie tych bezpiecznych w 100% jeżeli to ułatwi komuś życie, chociaż i tak trzeba uważać więc z drugiej strony mija się to z celem.

**Comment by MajestaKoza** [comment]
No akurat macie rację, ale lepiej je usunąć (w szczególności IGG-Games). W [tym komentarzu](https://www.reddit.com/r/PiratedGames/comments/ulsttu/comment/i7xbf32) akurat są dowody, dlaczego IGG jest niebezpieczne.

**Comment by streambase-project** [comment]
@streambase-project temat kontynuowany [w tym wątku](https://github.com/streambase-project/streambase/issues/209).
