### ISSUE TITLE
darmowatv

### ISSUE THREAD

**Issue by 89891383** [streambase-project/streambase#187]
https://tv-iptv.bid/ iptv live

**Comment by PWPiotrr** [comment]
wie ktoś jak załozyć konto ?

**Comment by adamek20151** [comment]
a jak tam konto założyc?

**Comment by 89891383** [comment]
znalazłem na telegramie że  login to iptv a hasło to live

**Comment by 89891383** [comment]
@adamek20151 @PWPiotrr

**Comment by PWPiotrr** [comment]
super dzieki :)

**Comment by streambase-project** [comment]
@89891383 domena zaaktualizowana.
