### ISSUE TITLE
darmowatv.github.io

### ISSUE THREAD

**Issue by adamek20151** [streambase-project/streambase#188]
strona nie działa po wpisaniu adresu przekierowuje na https://tv-iptv.bid

**Comment by praspp** [comment]
@adamek20151
https://tv-iptv.bid/ *login: iptv hasło: live*

**Comment by streambase-project** [comment]
@adamek20151 wszystkie informacje znajdują się już w bazie.

**Comment by Giver9414** [comment]
Site Not Found

**Comment by streambase-project** [comment]
@Giver9414 strony od wczoraj już nie ma w bazie.
