### ISSUE TITLE
działające iptv za darmo

### ISSUE THREAD

**Issue by ThePolishCat** [streambase-project/streambase#19]
https://iptvlister.com/category/poland/

sprawdziłem parę kanałów i działają

**Comment by streambase-project** [comment]
@TheCatIsThere dodane.

**Comment by TheCatIsThere** [comment]
wydaje mi się że bardziej ten link pasowałby do darmowej TV

**Comment by streambase-project** [comment]
@TheCatIsThere nie bardzo, nie jest to online.

**Comment by TheCatIsThere** [comment]
a ok
