### ISSUE TITLE
nowa grupa na telegram

### ISSUE THREAD

**Issue by disco2000PL** [streambase-project/streambase#190]
filmy lub seriale które sa blokowane na warezach
belfer itp.
link - https://t.me/online_vod_free

**Comment by streambase-project** [comment]
@disco2000PL dodane.

**Comment by disco2000PL** [comment]
w weekend chyba bedzie nowy link - zaproszenie, i zmiana na prywatny

**Comment by streambase-project** [comment]
@disco2000PL w przypadku zmian, pisz w tym samym zgłoszeniu lub otwórz nowe.
