### ISSUE TITLE
Cda,pl drm-free video links nie działa

### ISSUE THREAD

**Issue by StimShit** [streambase-project/streambase#191]
Czy wie ktoś może co się stało z tym botem na telegramie?

**Comment by streambase-project** [comment]
@StimShit ten bot raz działa, raz nie działa, trzeba po prostu próbować aż znów zacznie działać.

**Comment by disco2000PL** [comment]
możliwe że zostało konto zablokowane, jeśli za dużo jest osób które generuje linki to jest problem wtedy

**Comment by StimShit** [comment]
> możliwe że zostało konto zablokowane, jeśli za dużo jest osób które generuje linki to jest problem wtedy

Przykra sprawa

**Comment by disco2000PL** [comment]
wystarczy zmienic konto , a kont do cda jest masa wiec przez tydzień jedno przez tydzien nastepne i tak w kółko

**Comment by streambase-project** [comment]
@disco2000PL to powiedz to autorowi.
