### ISSUE TITLE
http://super-warez.eu/

### ISSUE THREAD

**Issue by robak29** [streambase-project/streambase#192]
Strona nie działa od wczorajsza ( od 9 godziny ) 

iNFO po wejściu na stronę : 

Serwer lub domena zostały zablokowane,
skontaktuj się z obsługą klienta.

[KONTAKT](https://www.cal.pl/kontakt)

**Comment by streambase-project** [comment]
@robak29 będziemy obserwować do tygodnia, może przeniosą się na inny hosting.

**Comment by disco2000PL** [comment]
z tego co wiem to serwer jest przenoszony gdzie indziej , bo serwerownia dostała jakieś info od jakiejś kurewki

**Comment by streambase-project** [comment]
@robak29 strona znów działa.

**Comment by cielon80** [comment]
strona działa zaraz mu sie dobiora do d.. za ta strone nie polecam wspolpracy z tym jegomościem

**Comment by streambase-project** [comment]
@cielon80 warez jak warez. Funkcjonuje bez zarzutu.
