### ISSUE TITLE
nie działa 

### ISSUE THREAD

**Issue by arek11x** [streambase-project/streambase#194]
https://animedao.com.ru/  Connection timed out Error code 522 
https://9anime.gs/ przekierowuje na https://aniwave.to/
https://www.cda.pl/Max-kun Konto zostało zablokowane.

**Comment by streambase-project** [comment]
https://animedao.com.ru/ - domena zaktualizowana do działającej.
https://9anime.gs/ - domena zaktualizowana.
https://www.cda.pl/Max-kun - usunięte.

**Comment by streambase-project** [comment]
@arek11x 

https://animedao.com.ru/ - domena zaktualizowana do działającej.
https://9anime.gs/ - domena zaktualizowana.
https://www.cda.pl/Max-kun - usunięte.
