### ISSUE TITLE
filecr malware

### ISSUE THREAD

**Issue by ThePolishCat** [streambase-project/streambase#196]
https://rentry.co/filecr_malware

**Comment by streambase-project** [comment]
@ThePolishCat ciekawa informacja natomiast nie wpłynie na usunięcie tej strony, dopóki strona posiada pliki, które opisuje (pomimo malware). Podobny temat został ostatnio poruszany w pewnym zgłoszeniu.

**Comment by Vegeta34pl** [comment]
> https://rentry.co/filecr_malware

Thx

**Comment by Vegeta34pl** [comment]
Dzięki
