### ISSUE TITLE
Nowa strona z audiobookami / ebookami do pobrania

### ISSUE THREAD

**Issue by JJcaoy** [streambase-project/streambase#200]
Dziś pobierając audiobooka, natknąłem się na chyba nową stronę z audiobookami i ebookami do pobrania.
https://bookflix.pro

**Comment by gzenio22** [comment]
Kurna szanuje :D

**Comment by JJcaoy** [comment]
Reklama w środku pliku była, ale chyba "legit" wygląda, prosta i co najważniejsze bez konta można przeglądać. Zadecydujecie sami czy dodać czy nie.

**Comment by streambase-project** [comment]
@JJcaoy dodano jedynie do działu z AudioBookami, póki co na stronie brak ebooków.

**Comment by JJcaoy** [comment]
Chyba coś ruszyło z ebookami. Admin mówił, że zaczynają na przemian wrzucać a/ebooki

**Comment by JJcaoy** [comment]
> @JJcaoy dodano, jedynie do działu z AudioBookami, póki co na stronie brak ebooków.

Chyba coś ruszyło z ebookami. Admin mówił, że zaczynają na przemian wrzucać a/ebooki

**Comment by streambase-project** [comment]
@JJcaoy dodano również do ebooków.
