### ISSUE TITLE
telegram bot chomikuj

### ISSUE THREAD

**Issue by prezes92k** [streambase-project/streambase#206]
Bot Chomikuj na telegramie w tym momencie nie działa

**Comment by robak29** [comment]
Należy poczekać i sprawdzić przez najbliższy miesiąc czy wstanie - jeśli nie to do usunięcia będzie.

**Comment by Montezuma0987** [comment]
Istnieje jeszcze szansa, że bot zacznie działać. Wszystko przez brak możliwość przedłużenia subskrypcji chomik mobile (tej za 5 zł), której oni używają do generowania. Niestety może to też oznaczać, że chomik próbuje ją usunąć :/

**Comment by Montezuma0987** [comment]
Chuj. Chomik usunął ową subskrypcję
![Screenshot_20230929-153026-458](https://github.com/streambase-project/streambase/assets/143293374/292f92c1-d8b1-4434-97ac-4db10857fb39)

**Comment by robak29** [comment]
"Witam serdecznie, z przykrością informujemy, że prace nad przywróceniem płatności w aplikacji mobilnej znacząco się wydłużają. Mamy nadzieję, że wznowienie działania nastąpi w przeciągu kilku miesięcy. Niestety chwilowo nie będzie możliwości aktywacji usługi Transferu Nielimitowanego a także zakupu Transferu Dodatkowego poprzez płatność Google Pay. Bardzo przepraszamy za niedogodności. Tymczasowo możemy polecić zakup pozostałych usług bezpośrednio przez stronę internetową. Niestety usługa transferu nielimitowanego nie jest obecnie dostępna."

Tak znajomemu odpisali na e-maila.

**Comment by Montezuma0987** [comment]
Ja pierdole, to zajebiście!

**Comment by Montezuma0987** [comment]
Zaktualizowali komunikat
![Screenshot_1](https://github.com/streambase-project/streambase/assets/143293374/cada8ece-4bf3-490e-9c6a-f5c66b9554a0)

**Comment by streambase-project** [comment]
@Montezuma0987 zatem tymczasowo będziemy musieli usunąć tego bota z bazy.
