### ISSUE TITLE
Usuńcie parę stron ponieważ NIE SĄ bezpieczne

### ISSUE THREAD

**Issue by MajestaKoza** [streambase-project/streambase#209]
Chciałabym Wam powiedzieć, że kilka stron niestety nie jest za bardzo zaufane, jeżeli chodzi o gry i repack-i. Są to m.in:

- IGG-Games/PCGamesTorrents (**w większości ich gier są koparki kryptowalut, zarówno jak i wirusy**, a także DRM z ich reklamą które po jego usunięciu gra przestaje działać. Na dodatek **każą wyłączyć Ci adblocka**, przez co próbują zainstalować na twoim komputerze porywacze przeglądarek)
- SteamUnlocked (wolne pobieranie, złośliwe przekierowania, a ponadto na ich stronie można znaleźć wydania gier ukradzione od IGG-Games.)
- AimHaven (Złośliwe przekierowujące reklamy)
- Ocean of Games (WYSOKIE ryzyko wirusów)
- Game3rb (fałszywe aczkolwiek złośliwe linki do pobrań)
i wiele więcej.
Jeśli pobierałeś/łaś coś z powyższych stron, najlepiej przeskanować każdy pobrany plik za pomocą [VirusTotal](https://www.virustotal.com/).

Jeżeli chodzi o inne strony z grami, proszę zajrzeć [na tę stronę](https://rentry.org/pgames) po zaufane źródła. Jeżeli chodzi o inny temat (np. filmy, programy, muzyka itd.), na Reddicie są bardzo dobre subreddity jak np. [ten](https://www.reddit.com/r/FREEMEDIAHECKYEAH/), albo [ten](https://www.reddit.com/r/Piracy/), który ma własny spis zaufanych stron (tzw. megathread).
Bądźmy bezpieczni w internecie ❤️

**Comment by Montezuma0987** [comment]
@MajestaKoza Temat bezpieczeństwa tych stron był już poruszany w jednym wątku. Nie zostaną one usunięte, dopóki serwują one pliki zgodne z opisem i wyglądające wiarygodnie. Ja osobiście jestem za zostawieniu tych stron

**Comment by MajestaKoza** [comment]
Ale większość ludzi na Reddicie nie cierpi tej strony ponieważ nie jest za bardzo bezpieczna, a ja się z nimi zgadzam; nie odpowiadam za zniszczony komputer ¯\_(ツ)_/¯

**Comment by Montezuma0987** [comment]
> Ale większość ludzi na Reddicie nie cierpi tych stron

Zgadzam się z tym, wystarczy wspomnieć o którejś z tych stron, a moderatorzy już usuwają wiadomość, ale to dalej nie jest powód do usunięcia tych stron

**Comment by streambase-project** [comment]
@MajestaKoza temat jest nam znany.

> Jeżeli chodzi o inne strony z grami, proszę zajrzeć [na tę stronę](https://rentry.org/pgames) po zaufane źródła. 

Nie ma czegoś takiego jak zaufane źródła czy bezpieczeństwo w piractwie, nawet scena może podłożyć nam nogę. Znamy źródła i alternatywy, natomiast nie są tutaj potrzebne. 

W pobieraniu pirackich materiałów trzeba być świadomym reklam, malware czy innych niespodzianek, nikt nie daje ci tego wszystkiego za nic, tak jak tobie się wydaje, wielu twórców/grupy chce albo zarobić, albo cię okraść. A te miejsca, które ty myślisz, że są obecnie zaufane, kiedyś pokażą jak bardzo zaufane są, czyli historia, która od lat zatacza koło, którą widać na podstawie wielu nadal istniejących stron.

> ale lepiej je usunąć (w szczególności IGG-Games). W [tym komentarzu](https://www.reddit.com/r/PiratedGames/comments/ulsttu/comment/i7xbf32) akurat są dowody, dlaczego IGG jest niebezpieczne.

Ponownie, żadna strona nie jest bezpieczna, póki wszystkie strony z bazy serwują nam pliki, które rzeczywiście mają w sobie to, co opisują, mimo niespodzianek, nie widzimy powodów do ich usunięcia, trzeba być świadomym, że nie ma czegoś takiego jak bezpieczeństwo przy pobieraniu crackowanych gier, torrentów itp., wojna trwa i będzie trwać.

**Comment by streambase-project** [comment]
> Widzę, że nigdy nie skanowaliście pobranych plików, czy zawierają wirusy bądź koparki kryptowalut.

Ciekawy argument. Ja widzę, że myślisz, że wszystko jest do wykrycia, otóż zaskoczę cię, nie jest. Nawet w rzekomo czystym pliku może kryć się coś, co nie zostanie przez Ciebie wykryte.

>  I tak nadal trzymam się anglojęzycznej strony, ponieważ jest lepiej zaufana.

Nie jest lepiej zaufana, po prostu istnieje dłużej, tam w zwyczaju udzielają się przeciętni userzy. Ja jestem realistą i widzę rynek piractwa na przestrzeni wielu lat, stąd moje stanowisko o tym, że nie ma czegoś takiego jak strony zaufane/bezpieczne w tym temacie, o którym rozmawiamy.

**Comment by streambase-project** [comment]
@MajestaKoza 

> Widzę, że nigdy nie skanowaliście pobranych plików, czy zawierają wirusy bądź koparki kryptowalut.

Ciekawy argument. Ja widzę, że myślisz, że wszystko jest do wykrycia, otóż zaskoczę cię, nie jest. Nawet w rzekomo czystym pliku może kryć się coś, co nie zostanie przez Ciebie wykryte.

>  I tak nadal trzymam się anglojęzycznej strony, ponieważ jest lepiej zaufana.

Nie jest lepiej zaufana, po prostu istnieje dłużej, tam w zwyczaju udzielają się przeciętni userzy. Ja jestem realistą i widzę rynek piractwa na przestrzeni wielu lat, stąd moje stanowisko o tym, że nie ma czegoś takiego jak strony zaufane/bezpieczne w tym temacie, o którym rozmawiamy.
