### ISSUE TITLE
Strona angielska z filmami 

### ISSUE THREAD

**Issue by leonzawodowiec12** [streambase-project/streambase#214]
https://myflixerz.to/

**Comment by streambase-project** [comment]
@streambase-project strona z identyczną bazą materiałów co połowa stron, które znajdują się w tym spisie, odrzucamy.

**Comment by streambase-project** [comment]
@leonzawodowiec12 strona z identyczną bazą materiałów co połowa stron, które znajdują się w tym spisie, odrzucamy.
