### ISSUE TITLE
nie działa 

### ISSUE THREAD

**Issue by shadowUE** [streambase-project/streambase#216]
https://iptvrun.com/cgi-sys/suspendedpage.cgi
https://up.antopie.org
https://theblues-thatjazz.com/

**Comment by streambase-project** [comment]
@shadowUE 

https://iptvrun.com - domena zaktualizowana do działającej.
https://up.antopie.org/ - usunięto.
https://theblues-thatjazz.com/ - strona działa, ale tylko przez http, zostaje.
