### ISSUE TITLE
Lista darmowych polskich stron z filmami i serialami online

### ISSUE THREAD

**Issue by arisu2115** [streambase-project/streambase#23]
Do wywalenia:
hdseans.pl - useless, nic tam nie działa
zobaczfilm.com - nic tam nie działa, co lepsze jak cofasz się do poprzedniej karty wyświetla się komunikat "Nie cwaniakował bym na twoim miejscu :P" XD
cdahd.co - nie działa
playz.cc - nic nowego od 2-3 miesięcy
3ksodus.cc - nie działa

**Comment by PLoliwi** [comment]
3ksodus.cc - pisałem z gościem szuka hostingu na stronę przez co strona ciężko chodzi wywala

**Comment by streambase-project** [comment]
@arisu2115 

1. HDseans nie jest useless, baza jest ogromna i codziennie dodają duże ilości materiałów — wystarczy się zalogować.
2. ZobaczFilm, z racji zakładki „Za darmo” i możliwości obejrzenie przez nią bezpłatnie materiałów zostaje, a komunikat, o którym piszesz występuje jedynie przy klikaniu PPM na stronę, tak zrobił autor nie wnikam, nie przeszkadza to w funkcjonowaniu strony.
3. CdaHD - usunięte.
4. PlayZ - listujemy strony, które mają w ofercie filmy bezpłatnie, wszystkie, jakie istnieją, bez względu czy ich baza jest aktualizowana, dopóki strona istnieje i coś można oglądać — zostaje.
5. 3ksodus - usunięte.
