### ISSUE TITLE
https://www.emailnator.com/

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#28]
Generator tymczasowych maili GMail. 
Wiele stron nie akceptuje już typowych generatorów email, które są rozpowszechnione w internecie. Dokładnie teraz z pomocą przychodzi Emailnator – Szybko dobrze I bez zbędnych formalność – Działa dosłownie wszędzie ( Facebook, twitter etc. )

**Comment by streambase-project** [comment]
@Wardzislaw dodane.
