### ISSUE TITLE
https://dreamsite.pro/

### ISSUE THREAD

**Issue by prezes92k** [streambase-project/streambase#3]
https://dreamsite.pro/
Zamknięte forum, zawiera większą bazę niż otwarte exsite.pl

**Comment by streambase-project** [comment]
@prezes92k zgadza się natomiast nie jest w spisie, ponieważ jest wyłącznie na zaproszenie.

**Comment by gzenio22** [comment]
w czym ta domena niby jest lepsza od otwartej XD

**Comment by prezes92k** [comment]
Wstawkami?
Posiada np. pozycje z canal plus, a takich na otwartej nie znajdziemy

śr., 1 mar 2023, 18:38 użytkownik gzenio22 ***@***.***>
napisał:
