### ISSUE TITLE
Kanały na telegramie udostępniające filmy i seriale

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#31]
https://t.me/magazynfilmow

https://t.me/calefilmypolskilektor

https://t.me/plflix

https://t.me/rosyjskie (filmy rosyjskie z polskim lektorem)

https://t.me/serialepolska

**Comment by streambase-project** [comment]
@Wardzislaw został utworzono specjalny dział Telegramy, dodane wszystko.
