### ISSUE TITLE
https://all-forum.cba.pl/index.php - Aktualizacja

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#36]
Forum jest wartościowe. Dostaje maile z informacją, jakie konta zostały dodane w dziale VIP w ostatnim czasie
Poniżej wysyłam link do screen'a wiadomości
https://i.ibb.co/5Gb012f/Screenshot-2023-03-23-11-50-43.png

**Comment by streambase-project** [comment]
@Wardzislaw dodane do działu płatnego z racji że na free nic nie ma.
