### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by gzenio22** [streambase-project/streambase#41]
https://t.me/+gE8lq_89jAllZTNi : Całe Filmy. Wymagana akceptacja administratora ale materiał aktualizowany niemal codziennie
 https://t.me/+Z40HOLYtiao5MWIy : Seriale PL : Podobna sytuacja jak wyżej wymagana akceptacja admina ale aktualizowane często
 https://t.me/+lLUhERT6AwhhOGU6 : Całe filmy PL Jak w powyższych różnica polega na tym że na tym kanale są wstawiane filmy tylko z polskim tłumaczeniem

**Comment by streambase-project** [comment]
@gzenio22 dodane.

**Comment by gzenio22** [comment]
https://t.me/filecr : Tu jeszcze kanał z oprogramowaniem :)

**Comment by streambase-project** [comment]
@gzenio22 ich strona jest w awesome-links.
