### ISSUE TITLE
https://rentry.co/revanced-build-pl

### ISSUE THREAD

**Issue by ThePolishCat** [streambase-project/streambase#5]
https://rentry.co/revanced-build-pl
tutorial budowy revanced napisany przezemnie
jeżeli jest zbyt chaotyczny to mogę poprawić

**Comment by streambase-project** [comment]
@TheCatIsThere na pewno graficzne leży, jeżeli się zgodzisz wprowadzę kilka zmian, stworze pod inny linkiem i podam ci kod do edycji?

**Comment by TheCatIsThere** [comment]
Spoko, nie ma problemu
