### ISSUE TITLE
gog-games.com przeniesienie strony do TOR

### ISSUE THREAD

**Issue by robak29** [streambase-project/streambase#52]
https://gog-games.com/

We have moved.
The site has been moved to the Tor network. You will need to install the Tor Browser then visit the link below in it. The link will NOT work in normal browsers (i.e. Google Chrome, Firefox, etc.

http://goggamespyi7b6ybpnpnlwhb4md6owgbijfsuj6z5hesqt3yfyz42rad.onion/

**Comment by streambase-project** [comment]
@robak29, póki ich strona daje informacje o przekierowaniu na TOR — zostaje, alternatywnie można wdrożyć dział z linkami .onion, lecz póki co nie ma propozycji na coś takiego.

**Comment by gzenio22** [comment]
mozna by to zrobic chetnie bym po zwiedzał Deep weba :D
