### ISSUE TITLE
Całe filmy NEW

### ISSUE THREAD

**Issue by gzenio22** [streambase-project/streambase#53]
https://t.me/+nu0SI019vBM5NWYy : Filmy do oglądania ale i z możliwością pobierania

**Comment by streambase-project** [comment]
@gzenio22 to jest zamiast czegoś obecnego czy jako dodatkowe?

**Comment by Wardzislaw** [comment]
@streambase-project To zupełnie inna grupa

**Comment by streambase-project** [comment]
@gzenio22 @Wardzislaw dodane.
