### ISSUE TITLE
Prywatne zagraniczne trackery torrent

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#54]
iptorrents.com (Podobno najlepsze)
passthepopcorn.me/
torrentday.com 
hd-torrents.org
hd-space.org
exoticaz.to (Do XXX)
femdomcult.org (Też do XXX)
gazellegames.net (Do gier)
bibliotik.me/ (Do książek)
broadcasthe.net/
animebytes.tv/ (Do anime)

Wiem, że nie ma działu do tego

**Comment by streambase-project** [comment]
@Wardzislaw mogę utworzyć na dniach taki dział jeżeli znajdzie się więcej topowych stron prywatnych.

**Comment by Wardzislaw** [comment]
@streambase-project Jeszcze mam:
speedapp.io 
redacted.ch
myanonamouse.net
adult-cinema-network.net

**Comment by Wardzislaw** [comment]
i bwtorrents.tv

**Comment by Wardzislaw** [comment]
pussytorrents.org
cheggit.me
seedfile.io
filelist.io
xbt.puntotorrent.com
bitgamer.ch
bitsexy.org
xspeeds.eu

Od groma tego jest...

**Comment by streambase-project** [comment]
@Wardzislaw wyselekcjonuj topkę, tak jak są Polskie, nie że część to same xxx.

**Comment by Wardzislaw** [comment]
@streambase-project Już się robi

Topka:
iptorrents.com
speedapp.io
redacted.ch
audionews.org
myanonamouse.net
bibliotik.me (do książek)
broadcasthe.net
passthepopcorn.me
animebytes.tv (do anime)
gazellegames.net (Do gier)

Według https://www.vpnmentor.com/blog/best-private-torrent-trackers/

Inne gdzieś znalezione (kolejność losowa):
cheggit.me
seedfile.io
xbt.puntotorrent.com
bitgamer.ch
xspeeds.eu
bwtorrents.tv
torrentday.com
hd-torrents.org
hd-space.org
xspeeds.eu
filelist.io

Z samym xxx (kolejność losowa):
gaytorrent.ru
bitsexy.org
pussytorrents.org
adult-cinema-network.net
exoticaz.to
femdomcult.org

**Comment by streambase-project** [comment]
@streambase-project jak już to zamieszczę tylko tą topke, szkoda wciskać jakieś byle jakie jak te poza nią.
