### ISSUE TITLE
Forum o crackowaniu kont, hackowaniu i więcej

### ISSUE THREAD

**Issue by ThePolishCat** [streambase-project/streambase#73]
https://cracked.io/

**Comment by Wardzislaw** [comment]
@ThePolishCat nie ma na to działu

**Comment by ThePolishCat** [comment]
@Wardzislaw  Raczej pasuje do awesome links

**Comment by streambase-project** [comment]
@ThePolishCat jest więcej for tego typu, ale nie ma w nich nic ciekawego, są też łatwo dostępne, póki co nie ma sensu tworzyć nowego działu, a w kwestii awesome-links, to pytanie co w tym forum jest wyjątkowego?

**Comment by ThePolishCat** [comment]
To jest chyba największe forum tego typu
