### ISSUE TITLE
kolejny telegram z kontami

### ISSUE THREAD

**Issue by Wavy512** [streambase-project/streambase#80]
tym razem konta to główna tematyka na tej grupie jest ich bardzo dużo https://t.me/kontownia

**Comment by streambase-project** [comment]
@Wavy512 konta niby sa, ale to chyba jakieś dziecko prowadzi, raczej słaby kontent.

**Comment by Wardzislaw** [comment]
@streambase-project To jego kanał

**Comment by streambase-project** [comment]
@streambase-project właściciel kanału reklamował różne serwery, ja osobiście nie jestem w stanie określić.

**Comment by Wavy512** [comment]
> 

własciwie to admin prowadzi ten telegram
