### ISSUE TITLE
Bardzo dobre mody Windowsa 10/11

### ISSUE THREAD

**Issue by Doppelgang3r** [streambase-project/streambase#83]
https://ghostspectre.the-ninja.jp/

Strona przekierowuje na kanał YT twórcy, w filmach poświęconym poszczególnym systemom można znaleźć linki do downloadu kierujące z powrotem na stronę podaną powyżej.

**Comment by streambase-project** [comment]
@Doppelgang3r mógłbyś nieco jaśniej? Przejrzałem parę materiałów z Windowsem i w opisie brak jakiekolwiek linku z dw. Daj jakiś konkretny materiał.

**Comment by Doppelgang3r** [comment]
Na dzień pisania prośby, link wyglądał tak jak powyżej, aktualnie zmienili domenę na "https://ghostcloud.ml/", która jest w wiecznym maintenance, dlatego pisałem o bezpośrednim wchodzeniu na podstronę obrazu z linku w opisie.

Co do obrazów - wzięty z pierwszego lepszego filmu z kanału (ostatni film "
Windows 11 22H2 Moment 2 vs Previous Build Windows 11 22H2") - https://ghostcloud.ml/wp1/w11-22h2-22621/

Z tego co widzę, wszystkie są schowane pod bit.ly, ale normalnie odnośniki przenoszą do strony konkretnego obrazu.

Nie można skopiować linku do podświetlenia w opisie filmu, podrzucę linki do filmów i screena z miejscem gdzie jest link do obrazu:
- https://youtu.be/WjwgzMcNL_M
- https://youtu.be/EXoBHxCvxlE
- https://youtu.be/nJ418uicpk8

![opisy_ss](https://user-images.githubusercontent.com/20521722/233211390-2392a914-fac9-4611-a99f-82b671a3e7a4.png)

Decyzja czy to wrzucić należy do Was ;)

**Comment by streambase-project** [comment]
@Doppelgang3r dodane.
