### ISSUE TITLE
Telewizja + Filmy

### ISSUE THREAD

**Issue by soldierfield12** [streambase-project/streambase#87]
Międzynarodowe TV:

https://streema.com/
https://www.squidtv.net/
https://wwitv.com/portal.htm
https://canlitv.center/hd3 (Głównie Turcja,Azerbejdżan i Bliski Wschód)
https://online-television.net/
https://tv-100.com/pl/ (Strona po Polsku ale bardzo dużo kanałów nie działa)

Polska TV (Bezpłatny okres próbny)
https://sweet.tv/pl/
https://www.filmbox.com

Platforma z TV Radiem i Telewizyjnymi programami:
https://www.coolstreaming.us/browse.html

Stare Polskie Filmy: (Możliwość napisów w innych językach)
https://easterneuropeanmovies.com/country/poland

Polskie Filmy z Angielskimi napisami:
https://theflixer.tv/country/PL

Rosyjskie filmy z polskimi napisami:
https://sovietmoviesonline.com/subtitles_languages/polish

Filmy + TV (Angielskie)
https://www.plex.tv/ (Potrzebna rejestracja)

Filmy Polskie:
https://adapter.pl/
https://etiudy.filmschool.lodz.pl/
https://www.filmdoo.com/polish/

Filmy Dokumentalne:
http://www.dokumentcyfrowo.pl/

Czeska i Słowacka TV:
https://www.spustit.cz/

Kilka stacji Niemieckiej TV:
https://www.ardmediathek.de/live

TV3 Litwa Łotwa Estonia (TV, Seriale, Sport i Wiadomości)
https://play.tv3.lt/

Bajki (Czechy)
https://decko.ceskatelevize.cz/

Kamery na żywo:
https://www.earthtv.com/en

Przydatne linki: (Nastawienie częstotliwości stacji TV i Radia na całym świecie)
https://fmscan.org/index.php
https://fmscan.org/net3.php?r=t&m=m&itu=POL (Polske Tv)
https://fmscan.org/net3.php?r=f&m=s&itu=POL (Polskie Radio)

**Comment by streambase-project** [comment]
@soldierfield12 na ten moment musimy odrzucić propozycję, ponieważ krótko mówiąc — większość nie nadaje się do bazy.

**Międzynarodowe TV — stąd moglibyśmy dodać dwie najlepsze strony, ale w obecnej sytuacji mamy już lepsze strony, także zostawimy sobie te na wypadek kiedy któraś byłaby niedostępna lub w przyszłości lepsza.

**Polska TV (Bezpłatny okres próbny)** — nie dodajemy stron, które nie są darmowe w dłuższej perspektywie.

**Platforma z TV Radiem i Telewizyjnymi programami** — nie mamy miejsca dla stron radiowych, natomiast jako strona z TV nie oferuje nic więcej co obecne jak dotąd źródła.

**Stare Polskie Filmy: (Możliwość napisów w innych językach)** - płatne.

**Polskie Filmy z Angielskimi napisami** — od tego mamy dział z angielskimi stronami i tam, póki co dodajemy już tylko topowe strony.

**Rosyjskie filmy z polskimi napisami — również od takich stron mamy dział ze stronami angielskimi, tam są napisy do każdego kraju.

**Filmy + TV (Angielskie)** - okrojona baza z darmowymi filmami, Plex jest dobry jako instancja z własną bazą, jako strona darmowa z filmami online jest mocno słaba, z tego powodu też, póki co nie dodajemy (może ktoś sprostować nasze podejście).

**Filmy Polskie** — płatne.

**Filmy Dokumentalne** — brak możliwości obejrzenia.

Wszystkie pozostałe zostawiam bez wyjaśnienia, w skrócie, nie nadają się, nie mamy albo odpowiedniego działu, albo nie jest to, nic wyjątkowego co powinno znaleźć się w bazie.
