### ISSUE TITLE
ReVanced Telegram

### ISSUE THREAD

**Issue by PLoliwi** [streambase-project/streambase#97]
ReVanced Telegram, gościu aktywnie dodaje

https://t.me/revancedrepository

**Comment by Wardzislaw** [comment]
@PLoliwi to samo znajdziesz na oficjalnej stronie

**Comment by ThePolishCat** [comment]
@Wardzislaw jakiej oficjalnej stronie? Revanced chyba ma tylko githuba, reszta może mieć wirusy itp

**Comment by PLoliwi** [comment]
> @PLoliwi to samo znajdziesz na oficjalnej stronie

A jaka jest ich oficjalna strona

**Comment by ThePolishCat** [comment]
> A jaka jest ich oficjalna strona
https://github.com/revanced

**Comment by streambase-project** [comment]
Mamy już podobne rozwiązanie w bazie, odrzucam.
