### ISSUE TITLE
Sport online

### ISSUE THREAD

**Issue by Wardzislaw** [streambase-project/streambase#98]
http://www.rojadirecta.eu/

**Comment by streambase-project** [comment]
@Wardzislaw ma duży minus, odrzuca z VPN/proxy. Jest ona w jakimś stopniu wyjątkowa nad tymi, które są obecnie?

**Comment by Wardzislaw** [comment]
@streambase-project na pierwszy rzut oka wygląda bogato

**Comment by gzenio22** [comment]
Rojadirecta to jedna z największych w europie stron z pirackimi transmisjami ostatnio RIAA sie na nich ostro sadzi

**Comment by streambase-project** [comment]
@gzenio22 @Wardzislaw wystarczająco, dodane.
